### ISSUE TITLE
这个插件有特殊标牌吗

### ISSUE THREAD

**Issue by wmzg666** [KingfuChan/MTEPlugin-for-EuroScope#1]
为什么加了插件但标牌没变，还和原来一样，什么都没变（除了鼠标）

**Comment by KingfuChan** [comment]
请阅读Readme和[EuroScope官方文档](https://www.euroscope.hu/wp/documentation-about-euroscope/)

**Comment by LeoChen98** [comment]
你需要手动修改标牌的item指向插件提供的item
