### ISSUE TITLE
回放下地速显示不正确

### ISSUE THREAD

**Issue by AaronZSAM101** [KingfuChan/MTEPlugin-for-EuroScope#10]
**版本4.0.0**
如题，在倍速回放下，地速显示`+++`。参照手册设置`MTEPlugin:GS/ModeThreshold`值为999或更大依旧。

在图中，两机均为刚离场的状态，地速也不可能增速到1000KMH以上呀.jpg
![image](https://github.com/KingfuChan/MTEPlugin-for-EuroScope/assets/60245950/e0f6f14c-b20f-412e-bc77-405e813ce0a5)

**Comment by KingfuChan** [comment]
经测试，在4x倍速下如果ModeThreshold设置为999确实会导致出现+++，但是如果设置为99999，即使在16x倍速下也能正常显示为报告地速。请尝试用更大的值。

**Comment by AaronZSAM101** [comment]
问题暂时解决了，若后续还有情况会再开issue，感谢解答！
