### ISSUE TITLE
DCT in Route Checker

### ISSUE THREAD

**Issue by ghost** [KingfuChan/MTEPlugin-for-EuroScope#11]
在最新下载的4.0预版本，如果RouteCheak的航路中存在有DCT（直飞）的话，会显示黄色的X标志。

航路如：MUGLO W34 VAPGU **DCT** ORAVA

**Comment by KingfuChan** [comment]
请详细描述你的问题，例如你提供的航路是飞行计划中的航路还是csv文件中定义的航路？相对应的另一部分航路是什么？

**Comment by ghost** [comment]
![image](https://github.com/KingfuChan/MTEPlugin-for-EuroScope/assets/165481603/e3cf0015-4f90-4540-bbce-cdb82af93061)
![image](https://github.com/KingfuChan/MTEPlugin-for-EuroScope/assets/165481603/88cdb38b-f872-4609-beed-d17110314181)
![image](https://github.com/KingfuChan/MTEPlugin-for-EuroScope/assets/165481603/179a837f-d08d-4270-8af2-df2e771015ba)
如果csv中定义了有DCT的航路,即使机组飞行计划的航路为正确的，都无法正常匹配，均显示为黄色的X标志

**Comment by KingfuChan** [comment]
请在csv中去除DCT内容再尝试，如在csv中更改为：
`BOTPU W47 VIGEK UPSUR W69 LUGVU`
按照目前的判定逻辑，飞机计划中的DCT会全部被去除后进行文本判定。
