### ISSUE TITLE
MA自定义下拉列表

### ISSUE THREAD

**Issue by XiaoZhang-store** [KingfuChan/MTEPlugin-for-EuroScope#12]
这是MA的设置文件，在plugin设置文件中添加了：MTEPlugin:MetricAltitudeTXT:MA.txt
[MA.txt](https://github.com/user-attachments/files/15873129/MA.txt)
但是这样es使用使用很短时间就会出现卡住的现象，请问如何进行解决，或者如何进行正确配置MA.txt

**Comment by XiaoZhang-store** [comment]
es版本3.2.9和3.2.3版本均会出现该问题，MTEP为最新4.0.0版本

**Comment by AaronZSAM101** [comment]
同custom MA使用，但未见异常，建议再次检查你的Plugin设置。
