### ISSUE TITLE
[FEAT REQ] CFL&SPD&VS Indicator

### ISSUE THREAD

**Issue by AaronZSAM101** [KingfuChan/MTEPlugin-for-EuroScope#15]
## CFL
在`MTEPlugIn.cpp`中，代码如下
```
	case TAG_ITEM_TYPE_CFL_FLX: {
		if (!FlightPlan.IsValid()) break;
		if (!m_TrackRecorder->IsCflAcknowledged(FlightPlan.GetCallsign())) {
			GetColorDefinition(SETTING_COLOR_CFL_CONFRM, pColorCode, pRGB);
		}
		int cflAlt = FlightPlan.GetControllerAssignedData().GetClearedAltitude();
		if (cflAlt == 2) { // cleared for visual approach
			PrintStr("VA");
		}
		else if (cflAlt == 1) { // cleared for ILS approach
			PrintStr("ILS");
		}
		else if (!IsCFLAssigned(FlightPlan)) { // no cleared level or CFL==RFL
			PrintStr("    ");
		}
```
看起来CFL在为空时会直接打印4个空字符，有机会修改成根据MA List的字符打印对应字符吗

## SPD
部分ATM系统会使用一些自定义化的调速显示，例如，`N180`代表调速180kts，而在部分ATM系统（比如台北EuroCAT）会使用`K18`来表示。初步设想是，能否定义速度前的显示字符，而后根据插件中的速度设置对速度单位进行设定，最后定义调速的数字字符数？
（如果有更好的逻辑会更棒）

## VS Indicator
如代码：
```
	case TAG_ITEM_TYPE_LVL_IND: {
		if (!RadarTarget.IsValid()) break;
		int vs = CalculateVerticalSpeed(RadarTarget);
		int thld = abs(GetPluginSetting<int>(SETTING_VS_THLD));
		PrintStr(vs >= thld ? "^" : (vs <= -thld ? "|" : ">"));
		break;
```
在不同的状态下会显示不同的VS Indicator，有机会做一下客制化吗？（还是因为台北EuroCAT，它的TAG标牌是相反的，左侧CFL右侧MCL，Indicator在平飞状态下由右指向左，与大陆的EuroCAT-X相反。（或者说，他应该就是由MCL指向CFL）。

**Comment by KingfuChan** [comment]
CFL与VS Indicator功能已完成，感谢建议。
至于SPD，我也没做assigned speed的item啊……这个功能或许topsky等插件提供了定制？

**Comment by AaronZSAM101** [comment]
> CFL与VS Indicator功能已完成，感谢建议。 至于SPD，我也没做assigned speed的item啊……这个功能或许topsky等插件提供了定制？

这个是因为之前有一个open assign spd的function，所以刚好引申出来问问有没有这个可能

**Comment by AaronZSAM101** [comment]
> CFL与VS Indicator功能已完成，感谢建议。
> 
> 至于SPD，我也没做assigned speed的item啊……这个功能或许topsky等插件提供了定制？

刚查阅了TopSky插件文档，没有对Speed的item前字母进行自定义的可能，只能根据是否COOPANS（就是俗称的B版）进行不一样的显示。

**Comment by KingfuChan** [comment]
> > CFL与VS Indicator功能已完成，感谢建议。 至于SPD，我也没做assigned speed的item啊……这个功能或许topsky等插件提供了定制？
> 
> 这个是因为之前有一个open assign spd的function，所以刚好引申出来问问有没有这个可能

暂时没有计划增加ASP相关的item，ASP list也没有维护计划，因为这个逻辑与其他的功能差异较大。

**Comment by AaronZSAM101** [comment]
> > > CFL与VS Indicator功能已完成，感谢建议。 至于SPD，我也没做assigned speed的item啊……这个功能或许topsky等插件提供了定制？
> > 
> > 
> > 这个是因为之前有一个open assign spd的function，所以刚好引申出来问问有没有这个可能
> 
> 暂时没有计划增加ASP相关的item，ASP list也没有维护计划，因为这个逻辑与其他的功能差异较大。

Thanks for reply~
