### ISSUE TITLE
关于CFL高度的颜色问题

### ISSUE THREAD

**Issue by AaronZSAM101** [KingfuChan/MTEPlugin-for-EuroScope#3]
参考[上海进近视频](https://www.bilibili.com/video/BV1mG4y1m7Ap/)

![image](https://github.com/KingfuChan/MTEPlugin-for-EuroScope/assets/60245950/bb7748d5-661f-4604-872b-9665361dbbd3)
如图，飞机在移交出，被下级管制单位接受后，**一整个牌子**会显示橙色。在ES设置中，通常是将Symbology的Datablock-Redundant项改成橙色

但在观察MTEP的代码后，CFL的确认过程是，选中高度后，然后CFL颜色变为Redundant的颜色（即高度未确认状态），如果我改成橙色的话，CFL待确认高度也会变成橙色，就不是白色了。

请问这个颜色可以在后续的开发中强制变为白色吗？或是加入个自定义项目？

万分感谢，辛苦啦！

**Comment by KingfuChan** [comment]
目前准备发新版，暂未包括此功能，后续计划加入自定义颜色功能，时间待定

**Comment by AaronZSAM101** [comment]
> 目前准备发新版，暂未包括此功能，后续计划加入自定义颜色功能，时间待定

okok 辛苦！

**Comment by KingfuChan** [comment]
自定义颜色功能是可以做的，但是移交后依旧会在下一次雷达位置刷新后变为整个牌子的颜色，这是由于这个模块仅记录已经跟踪的（Tracked）飞机，移交后记录会被擦除。如果要实现视频中的功能，需要进一步对架构进行调整，暂未有相关规划。

**Comment by AaronZSAM101** [comment]
提供一个参考：
其实之前我观察过隔壁SinoTAG的功能，他们的做法应该就是直接把这个CFL高度待确认的颜色写死，然后移交给下级单位，被接走后整个牌子颜色全部一样了，再之后有任何高度更新牌子颜色都是统一的，且高度有变化的话他都会继续有变化。
