### ISSUE TITLE
[feature request] any chance to add a command/menu action to switch QNH/QFE mode of specific airport

### ISSUE THREAD

**Issue by LeoChen98** [KingfuChan/MTEPlugin-for-EuroScope#4]
Description: Some of the airports using QFE altitude also able to operate with QNH altitude. Is there any chance to add a command or menu action to switch between that two operation mode?

For example, the picture is showing an aircraft approaching ZWSH which was operating RNP STAR and APCH which are allowed to operate under QNH altitude. The requesting feature is to switch the altitude display between QFE and QNH.

![15b5d5fa33bd4d0819ba6bd3d306c49b](https://github.com/KingfuChan/MTEPlugin-for-EuroScope/assets/26154152/da0c99e0-c881-4f71-9b41-fc27904fa57e)

**Comment by KingfuChan** [comment]
There's already a command line function to switch QFE/QNH of specific airpot. Please refer to https://github.com/KingfuChan/MTEPlugin-for-EuroScope#tl---command-line-functions.
