### ISSUE TITLE
关于速度Menu的一个小建议

### ISSUE THREAD

**Issue by AaronZSAM101** [KingfuChan/MTEPlugin-for-EuroScope#6]
如下图，在1080p屏幕上，这个menu会显示的非常大，个人认为不利于进行雷达扫视及飞机数据的监控（？）
![image](https://github.com/KingfuChan/MTEPlugin-for-EuroScope/assets/60245950/85bde8da-48dd-41a5-852d-838f9bdc38cc)

如有机会的话，能否像CFL list一样，单独出一个配置文件，以减小这个Menu的宽度？

**Comment by KingfuChan** [comment]
该项使用率评估较低，增加配置文件开发成本过大，暂时不对该项进行维护。

**Comment by AaronZSAM101** [comment]
没事 Topsky够用了 现在这个东西阳间一些了
