### ISSUE TITLE
[feat req] 根据英米制变化，调整item位数

### ISSUE THREAD

**Issue by AaronZSAM101** [KingfuChan/MTEPlugin-for-EuroScope#8]
如图，在全局英制的情况下，使用CFL时，位数仍为四位数的空格，能否根据单位情况灵活调整该项目的位数？
![image](https://github.com/KingfuChan/MTEPlugin-for-EuroScope/assets/60245950/e82d6435-7ab8-4899-b586-c1f8bda0ea09)

**Comment by KingfuChan** [comment]
事实上CFL给出为英制、ILS时，item均只占用3个字符，为VA时占用2个字符。至于出现空格的原因请检查tag设置中的minimum position项。
